[package]
name = "VeytosMarketplace"
version = "0.0.1"
upgrade_policy = "compatible"

[addresses]
marketplace = "_"

[dev-addresses]
marketplace = "0xbeef"

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "831c39cff4c5a8ead98ddffe0edfc4ba51623e91"
subdir = "aptos-move/framework/aptos-framework"

[dependencies.AptosTokenObjects]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "831c39cff4c5a8ead98ddffe0edfc4ba51623e91"
subdir = "aptos-move/framework/aptos-token-objects"

[dependencies.AptosToken]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "831c39cff4c5a8ead98ddffe0edfc4ba51623e91"
subdir = "aptos-move/framework/aptos-token"
