import Link from 'next/link';
import { ArrowUpRight,ArrowRight } from 'lucide-react';
import { brand } from '@mintos/config';
import { discovery } from '@/lib/data';
import { Artwork } from '@/components/artwork';
import { DropStatus,WalletAddress,MintProgress } from '@/components/chain-ui';
import { DropCard,CollectionsTable } from '@/components/cards';
import { SectionHeader,EmptyState,ErrorState,PriceDisplay } from '@/components/ui';
import { dropStatus } from '@veytos/aptos/domain';
export const dynamic='force-dynamic';
export default async function Home(){const {drops,errors}=await discovery();const featured=drops[0];const now=BigInt(Math.floor(Date.now()/1000));const live=drops.filter(d=>dropStatus(d,now)==='LIVE');const upcoming=drops.filter(d=>dropStatus(d,now)==='UPCOMING');return <>
<div className="page-intro"><div><span className="eyebrow">ONE ECOSYSTEM. EVERY COLLECTION.</span><h1>{brand.tagline}</h1></div><Link href="/explore" className="text-link">Find your next collectible <ArrowUpRight size={18}/></Link></div>
{errors>0&&<ErrorState/>}
{featured?<section className="featured"><Link className="featured-art" href={`/collection/${featured.address}`}><Artwork uri={featured.terms.collection_uri} name={featured.terms.name} large/><span className="feature-index">01 / ON THE LAUNCHPAD</span></Link><div className="featured-copy"><div className="between"><span className="eyebrow">FEATURED DROP</span><DropStatus drop={featured}/></div><div><h2>{featured.terms.name}</h2><p className="creator-line">By <WalletAddress address={featured.terms.creator}/></p><p className="description">{featured.terms.description}</p></div><div className="featured-stats"><div><span className="caption muted">Mint price</span><strong><PriceDisplay octas={featured.terms.unit_price}/></strong></div><div><span className="caption muted">Collection size</span><strong>{featured.terms.max_supply}<small> items</small></strong></div></div><MintProgress minted={featured.minted} supply={featured.terms.max_supply}/><Link href={`/collection/${featured.address}`} className="button primary">Explore collection <ArrowUpRight size={18}/></Link></div></section>:<EmptyState title="The next chapter starts here" description="New Aptos collections will appear as they launch."><Link className="button primary" href="/explore">Explore collections <ArrowRight size={16}/></Link></EmptyState>}
<section className="section"><SectionHeader title="On the launchpad" subtitle="Real collections. Live mint counts." href="/explore"/>{drops.length?<CollectionsTable drops={drops}/>:<EmptyState title="No collections yet" description="This space is reserved for real launches on Aptos."/>}</section>
<section className="og-section"><div className="og-emblem" aria-hidden="true">OG<span>APTOS</span></div><div><span className="eyebrow">THE ORIGINALS</span><h2>OG Aptos Collections</h2><p>The collections that started it all deserve a place in what comes next.</p><span className="coming-note">Historical collection discovery is on its way.</span></div><span className="og-number" aria-hidden="true">↗</span></section>
<section className="section"><SectionHeader title="Live drops" subtitle="Discover something at the beginning." href="/drops"/>{live.length?<div className="card-grid">{live.map(d=><DropCard key={d.address} drop={d}/>)}</div>:<EmptyState title="No live drops right now" description="Good collections take time. Check upcoming launches."/>}</section>
<section className="section"><SectionHeader title="Coming next" subtitle="A little anticipation is part of collecting."/>{upcoming.length?<div className="card-grid">{upcoming.map(d=><DropCard key={d.address} drop={d}/>)}</div>:<div className="quiet-empty"><span className="status"><i/>UPCOMING</span><p>No scheduled drops yet.</p><Link href="/drops" className="text-link">Explore the launchpad <ArrowUpRight size={16}/></Link></div>}</section>
</>;}
