import Link from 'next/link';
import { ArrowUpRight } from 'lucide-react';
import type { Asset,Drop } from '@veytos/aptos/types';
import { Artwork } from './artwork';
import { DropStatus,MintProgress,WalletAddress } from './chain-ui';
import { PriceDisplay } from './ui';
export function DropCard({drop}:{drop:Drop}){return <article className="drop-card"><Link href={`/collection/${drop.address}`} className="card-image"><Artwork uri={drop.terms.collection_uri} name={drop.terms.name}/><span className="image-status"><DropStatus drop={drop}/></span><span className="card-arrow"><ArrowUpRight size={20}/></span></Link><div className="card-body"><div className="between"><h3><Link href={`/collection/${drop.address}`}>{drop.terms.name}</Link></h3><span className="caption muted">DA</span></div><p className="caption muted">Creator <WalletAddress address={drop.terms.creator}/></p><div className="between card-price"><span className="caption muted">Mint price</span><PriceDisplay octas={drop.terms.unit_price}/></div><MintProgress minted={drop.minted} supply={drop.terms.max_supply}/></div></article>;}
export const CollectionCard=DropCard;
export function NFTCard({asset}:{asset:Asset}){return <Link href={`/nft/${asset.address}`} className="nft-card"><Artwork uri={asset.uri} name={asset.name}/><div className="card-body"><span className="eyebrow">DIGITAL ASSET</span><h3>{asset.name||'Untitled NFT'}</h3><span className="caption muted">View asset <ArrowUpRight size={14}/></span></div></Link>;}
export function CollectionsTable({drops}:{drops:Drop[]}){return <div className="table-wrap"><table className="collections-table"><thead><tr><th scope="col">Collection</th><th scope="col">Mint price</th><th scope="col" className="optional-column">Minted / supply</th><th scope="col" className="optional-column">Status</th><th scope="col"><span className="sr-only">Open</span></th></tr></thead><tbody>{drops.map((drop,i)=><tr key={drop.address}><td><Link className="table-collection" href={`/collection/${drop.address}`}><span className="rank">{String(i+1).padStart(2,'0')}</span><span className="table-avatar"><Artwork uri={drop.terms.collection_uri} name={drop.terms.name}/></span><span><strong>{drop.terms.name}</strong><small>Aptos · Digital Asset</small></span></Link></td><td><PriceDisplay octas={drop.terms.unit_price}/></td><td className="optional-column numeric">{drop.minted}<span className="muted"> / {drop.terms.max_supply}</span></td><td className="optional-column"><DropStatus drop={drop}/></td><td><Link aria-label={`Open ${drop.terms.name}`} href={`/collection/${drop.address}`}><ArrowUpRight size={18}/></Link></td></tr>)}</tbody></table></div>;}
