import Link from 'next/link';
import { ArrowUpRight } from 'lucide-react';
import type {Drop} from '@veytos/aptos/types';
import { Artwork } from './artwork';
import { DropStatus,DropActionLabel,MintProgress,WalletAddress } from './chain-ui';
import { PriceDisplay } from './ui';
export function DropCard({drop}:{drop:Drop}){return <article className="drop-card"><Link href={`/collection/${drop.address}`} className="card-image"><Artwork uri={drop.terms.collection_uri} name={drop.terms.name}/><span className="image-status"><DropStatus drop={drop}/></span></Link><div className="card-body"><h3><Link href={`/collection/${drop.address}`}>{drop.terms.name}</Link></h3><p className="caption muted">By <WalletAddress address={drop.terms.creator}/></p><div className="between card-price"><span className="caption muted">Mint price</span><PriceDisplay octas={drop.terms.unit_price}/></div><MintProgress minted={drop.minted} supply={drop.terms.max_supply}/><Link className="card-cta" href={`/collection/${drop.address}`}><DropActionLabel drop={drop}/><ArrowUpRight size={14}/></Link></div></article>;}
export function FeaturedDrop({drop}:{drop:Drop}){return <article className="launch-feature"><Link className="launch-feature-art" href={`/collection/${drop.address}`}><Artwork uri={drop.terms.collection_uri} name={drop.terms.name} large/><span className="image-status"><DropStatus drop={drop}/></span></Link><div className="launch-feature-copy"><div><span className="eyebrow">FEATURED DROP</span><h2>{drop.terms.name}</h2><p className="creator-line">By <WalletAddress address={drop.terms.creator}/></p><p className="description">{drop.terms.description}</p></div><div className="launch-feature-facts"><div><span>Mint price</span><strong><PriceDisplay octas={drop.terms.unit_price}/></strong></div><div><span>Supply</span><strong>{drop.terms.max_supply}</strong></div></div><MintProgress minted={drop.minted} supply={drop.terms.max_supply}/><Link className="button primary" href={`/collection/${drop.address}`}><DropActionLabel drop={drop}/><ArrowUpRight size={16}/></Link></div></article>;}
export function CollectionsTable({drops}:{drops:Drop[]}){return <div className="table-wrap"><table className="collections-table"><thead><tr><th scope="col">Collection</th><th scope="col">Mint price</th><th scope="col" className="optional-column">Minted / supply</th><th scope="col" className="optional-column">Status</th><th scope="col"><span className="sr-only">Open</span></th></tr></thead><tbody>{drops.map((drop,i)=><tr key={drop.address}><td><Link className="table-collection" href={`/collection/${drop.address}`}><span className="rank">{String(i+1).padStart(2,'0')}</span><span className="table-avatar"><Artwork uri={drop.terms.collection_uri} name={drop.terms.name}/></span><span><strong>{drop.terms.name}</strong><small>Aptos · Digital Asset</small></span></Link></td><td><PriceDisplay octas={drop.terms.unit_price}/></td><td className="optional-column numeric">{drop.minted}<span className="muted"> / {drop.terms.max_supply}</span></td><td className="optional-column"><DropStatus drop={drop}/></td><td><Link aria-label={`Open ${drop.terms.name}`} href={`/collection/${drop.address}`}><ArrowUpRight size={18}/></Link></td></tr>)}</tbody></table></div>;}
