[package]
name = "MintosLaunchpad"
version = "0.0.1"
upgrade_policy = "compatible"

[addresses]
launchpad = "_"

[dev-addresses]
launchpad = "0xcafe"

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "1b116b414ccc1d860fa72160d9b9a770e8d8e88f"
subdir = "aptos-move/framework/aptos-framework"

[dependencies.AptosTokenObjects]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "1b116b414ccc1d860fa72160d9b9a770e8d8e88f"
subdir = "aptos-move/framework/aptos-token-objects"
