import {beforeEach,expect,test,vi} from 'vitest';
import {fireEvent,render,screen,waitFor} from '@testing-library/react';
import {QueryClient,QueryClientProvider} from '@tanstack/react-query';
import type {Drop,PendingMint} from '@veytos/aptos/types';
const mocks=vi.hoisted(()=>({wallet:{connected:true,account:{address:{toString:()=> '0x3'}},network:{chainId:2},signAndSubmitTransaction:vi.fn()},eligibility:vi.fn(),reconcile:vi.fn(),mintPayload:vi.fn(),refresh:vi.fn(),toastShow:vi.fn(),toastDismiss:vi.fn()}));
vi.mock('@aptos-labs/wallet-adapter-react',()=>({useWallet:()=>mocks.wallet}));
vi.mock('next/navigation',()=>({useRouter:()=>({refresh:mocks.refresh})}));
vi.mock('@/lib/chain',()=>({chain:()=>mocks}));
vi.mock('@/components/wallet',()=>({WalletButton:()=> <button>Connect to mint</button>}));
vi.mock('@/components/artwork',()=>({Artwork:()=> <span>Artwork unavailable</span>}));
vi.mock('@/components/transaction-toasts',()=>({useTransactionToast:()=>({show:mocks.toastShow,dismiss:mocks.toastDismiss})}));
import {MintPanel} from '../src/features/mint-panel';
const drop:Drop={address:'0x2',collection:'0x4',finalized:true,creator_paused:false,admin_paused:false,minted:'2',uploaded:'100',terms:{creator:'0x5',name:'TEST FIXTURE',description:'',collection_uri:'',max_supply:'100',unit_price:'10000000',wallet_limit:'10',transaction_limit:'5',start_seconds:'0',end_seconds:'0',royalty_bps:'750',fee_bps:'500'}};
const hash='0x'+'a'.repeat(64);
const moduleAddress='0x'+'1'.padStart(64,'0');
const key=`veytos:mint:testnet:${moduleAddress}:0x2`;
const pending:PendingMint={hash,sender:'0x3',drop:'0x2',quantity:1,unitPrice:'10000000',network:'testnet',module:moduleAddress};
function eligibility(d=drop,walletMinted='0'){return {drop:d,walletMinted,now:'100',chainId:2,paused:false};}
function mount(d=drop){const client=new QueryClient({defaultOptions:{queries:{retry:false,gcTime:0}}});return render(<QueryClientProvider client={client}><MintPanel initial={d}/></QueryClientProvider>);}
beforeEach(()=>{vi.clearAllMocks();mocks.wallet.connected=true;mocks.wallet.network.chainId=2;mocks.eligibility.mockResolvedValue(eligibility());mocks.mintPayload.mockReturnValue({function:'0x1::launchpad::mint',functionArguments:[]});});
async function ready(){await waitFor(()=>expect(screen.getByRole('button',{name:'Review mint'}).hasAttribute('disabled')).toBe(false));}
async function confirm(){await ready();fireEvent.click(screen.getByRole('button',{name:'Review mint'}));await waitFor(()=>expect(screen.getByRole('dialog').hasAttribute('open')).toBe(true));fireEvent.click(screen.getByRole('button',{name:'Confirm in wallet'}));}
test('sold-out rendering and closed review never throw',async()=>{const sold={...drop,minted:'100'};mocks.eligibility.mockResolvedValue(eligibility(sold));mount(sold);expect((await screen.findByRole('button',{name:'Sold out'})).hasAttribute('disabled')).toBe(true);expect(screen.queryByRole('dialog')).toBe(null);});
test('exhausted wallet allocation renders a disabled action',async()=>{mocks.eligibility.mockResolvedValue(eligibility(drop,'10'));mount();expect((await screen.findByRole('button',{name:'Wallet limit reached'})).hasAttribute('disabled')).toBe(true);});
test('eligibility loading is render-safe and cannot open review',()=>{mocks.eligibility.mockReturnValue(new Promise(()=>{}));mount();expect(screen.getByRole('button',{name:'Review mint'}).hasAttribute('disabled')).toBe(true);expect(screen.queryByRole('dialog')).toBe(null);});
test('disconnected wallet renders connection action',()=>{mocks.wallet.connected=false;mount();expect(screen.getByRole('button',{name:'Connect to mint'})).toBeTruthy();});
test('wrong network prevents review',async()=>{mocks.wallet.network.chainId=1;mount();expect(await screen.findByRole('alert')).toHaveProperty('textContent',expect.stringContaining('Switch your wallet to Aptos testnet'));expect(screen.queryByRole('button',{name:'Review mint'})).toBe(null);});
test('review displays included 5 percent fee and exact proceeds',async()=>{mount();await ready();fireEvent.click(screen.getByRole('button',{name:'Review mint'}));expect(await screen.findByRole('dialog')).toHaveProperty('textContent',expect.stringContaining('0.005'));expect(screen.getByRole('dialog').textContent).toContain('0.095');});
test('fresh supply change rejects quantity before signature',async()=>{mount();await ready();fireEvent.click(screen.getByRole('button',{name:'Increase quantity'}));mocks.eligibility.mockResolvedValue(eligibility({...drop,minted:'99'}));fireEvent.click(screen.getByRole('button',{name:'Review mint'}));await screen.findByRole('status');expect(mocks.wallet.signAndSubmitTransaction).not.toHaveBeenCalled();expect(screen.queryByRole('dialog')).toBe(null);});
test('adapter exception without hash is unknown and does not retry',async()=>{mocks.wallet.signAndSubmitTransaction.mockRejectedValue(new Error('Adapter disconnected'));mount();await confirm();expect(await screen.findByText(/No transaction hash was returned/)).toBeTruthy();expect(JSON.parse(localStorage.getItem(key)!).hash).toBe('');expect(mocks.wallet.signAndSubmitTransaction).toHaveBeenCalledTimes(1);expect(screen.getByRole('button',{name:'Clear unsubmitted request'}).hasAttribute('disabled')).toBe(true);});
test('explicit rejection clears unsubmitted record',async()=>{mocks.wallet.signAndSubmitTransaction.mockRejectedValue(Object.assign(new Error('User rejected'),{code:4001}));mount();await confirm();await screen.findByText(/Request cancelled/);expect(localStorage.getItem(key)).toBe(null);});
test('known hash survives RPC timeout and reload recovery reaches toast success',async()=>{localStorage.setItem(key,JSON.stringify(pending));mocks.reconcile.mockRejectedValueOnce(new Error('RPC timeout')).mockResolvedValueOnce({status:'success',assets:[{address:'0x6',uri:'',name:'Verified token'}]});mount();fireEvent.click(await screen.findByRole('button',{name:'Check transaction status'}));await waitFor(()=>expect(mocks.toastShow).toHaveBeenCalledWith(expect.objectContaining({tone:'unknown'})));expect(JSON.parse(localStorage.getItem(key)!).hash).toBe(hash);fireEvent.click(screen.getByRole('button',{name:'Check transaction status'}));await waitFor(()=>expect(mocks.toastShow).toHaveBeenCalledWith(expect.objectContaining({title:'Mint successful',tone:'success',message:'1 NFT minted to your wallet.',href:expect.stringContaining(hash)})));expect(screen.queryByText('Verified token')).toBe(null);expect(localStorage.getItem(key)).toBe(null);expect(mocks.refresh).toHaveBeenCalled();expect(mocks.wallet.signAndSubmitTransaction).not.toHaveBeenCalled();});
test('committed abort is a failure and releases recovery record',async()=>{localStorage.setItem(key,JSON.stringify(pending));mocks.reconcile.mockResolvedValue({status:'failed',message:'ESUPPLY'});mount();fireEvent.click(await screen.findByRole('button',{name:'Check transaction status'}));await screen.findByText(/This quantity is no longer available/);expect(localStorage.getItem(key)).toBe(null);});
test('interrupted pre-hash record is never automatically submitted',async()=>{localStorage.setItem(key,JSON.stringify({...pending,hash:''}));mount();await screen.findByText(/A wallet request was interrupted/);expect(mocks.wallet.signAndSubmitTransaction).not.toHaveBeenCalled();fireEvent.click(screen.getByRole('checkbox'));fireEvent.click(screen.getByRole('button',{name:'Clear unsubmitted request'}));expect(localStorage.getItem(key)).toBe(null);expect(mocks.wallet.signAndSubmitTransaction).not.toHaveBeenCalled();});
