import { discovery } from '@/lib/data';
import { Explore } from '@/features/explore';
import {ErrorState,EmptyState} from '@/components/ui';
import {marketplaceBrowse} from '@/lib/marketplace-data';
import {MarketplaceListingGrid} from '@/components/marketplace-browse';
import {parseApt} from '../../../../../packages/domain/src/money';
export const dynamic='force-dynamic';
export const metadata={title:'Explore'};
function price(value?:string){try{return value?parseApt(value).toString():undefined;}catch{return undefined;}}
export default async function Page({searchParams}:{searchParams:Promise<{q?:string;standard?:string;collection?:string;min?:string;max?:string;sort?:string}>}){const params=await searchParams;const [data,market]=await Promise.all([discovery(),marketplaceBrowse({standard:params.standard,collection:params.collection||params.q,minPrice:price(params.min),maxPrice:price(params.max),sort:params.sort})]);return <><div className="page-title"><span className="eyebrow">THE APTOS COLLECTION</span><h1>Explore</h1><p>Browse real testnet listings and launchpad collections.</p></div><section className="section"><div className="section-heading"><div><h2>Marketplace</h2><p className="muted">Active listings indexed from verified VEYTOS events.</p></div></div><form className="market-filters"><select name="standard" defaultValue={params.standard||''}><option value="">V1 + V2</option><option value="v1">Token V1</option><option value="v2">Digital Asset V2</option></select><input name="collection" defaultValue={params.collection||''} placeholder="Collection identity" aria-label="Collection identity"/><input name="min" inputMode="decimal" defaultValue={params.min||''} placeholder="Min APT" aria-label="Minimum price in APT"/><input name="max" inputMode="decimal" defaultValue={params.max||''} placeholder="Max APT" aria-label="Maximum price in APT"/><select name="sort" defaultValue={params.sort||'recent'}><option value="recent">Recently listed</option><option value="price-asc">Price: low to high</option><option value="price-desc">Price: high to low</option></select><button className="button" type="submit">Apply</button></form>{market.items.length?<MarketplaceListingGrid items={market.items}/>:<EmptyState title={market.failed?'Marketplace data is temporarily unavailable':'No active listings'} description={market.failed?'The browsing projection could not be reached. Trading pages continue to verify Aptos directly.':market.configured?'No listings match these filters.':'Marketplace browsing is unavailable until the beta indexer database is configured.'}/>}</section><section className="section"><div className="section-heading"><div><h2>Launchpad collections</h2><p className="muted">Live state read from the VEYTOS launchpad.</p></div></div>{data.errors>0&&<ErrorState/>}<Explore drops={data.drops} initialQuery={params.q||''}/></section></>;}
