'use client';
import {useEffect,useRef,useState} from 'react';
import {useQuery,useQueryClient} from '@tanstack/react-query';
import {useWallet} from '@aptos-labs/wallet-adapter-react';
import {ArrowUpRight,Check,ShieldCheck,X,Minus,Plus} from 'lucide-react';
import {brand} from '@mintos/config';
import {dropStatus,isUnresolved,networkMatches,readableError,validateQuantity,previewMint} from '@veytos/aptos/domain';
import type {Asset,Drop,PendingMint,TransactionPhase} from '@veytos/aptos/types';
import {pendingMintSchema,transactionTransition,definitiveRejection} from '@veytos/aptos/recovery';
import {chain} from '@/lib/chain';
import {explorer,network,packageAddress} from '@/lib/config';
import {WalletButton} from '@/components/wallet';
import {DropStatus,MintProgress,Countdown} from '@/components/chain-ui';
import {PriceDisplay,ExternalLink} from '@/components/ui';
import {Artwork} from '@/components/artwork';
import {trackBetaEvent} from '@/components/beta-analytics';
import {reportClientError} from '@/lib/observability';
export function QuantitySelector({value,max,disabled,onChange}:{value:number;max:number;disabled:boolean;onChange:(n:number)=>void}){return <div className="quantity"><button aria-label="Decrease quantity" disabled={disabled||value<=1} onClick={()=>onChange(value-1)}><Minus size={16}/></button><output aria-label="Mint quantity">{value}</output><button aria-label="Increase quantity" disabled={disabled||value>=max} onClick={()=>onChange(value+1)}><Plus size={16}/></button></div>;}
export function TransactionStatus({phase,hash,message}:{phase:TransactionPhase;hash?:string;message:string}){return <div className={`transaction-status ${phase==='success'?'success':phase==='failure'?'error':''}`} role="status" aria-live="polite"><span className="eyebrow">{phase==='wallet'?'WAITING FOR WALLET':phase.toUpperCase()}</span><p>{message}</p>{hash&&<ExternalLink href={explorer('txn',hash)}>View transaction</ExternalLink>}</div>;}
export function MintPanel({initial}:{initial:Drop}){
 const wallet=useWallet();const address=wallet.account?.address.toString();const client=useQueryClient();const dialog=useRef<HTMLDialogElement>(null);const signing=useRef(false);
 const [recoveryHash,setRecoveryHash]=useState(''),[checkedWallet,setCheckedWallet]=useState(false);
 const [quantity,setQuantity]=useState(1),[phase,setPhase]=useState<TransactionPhase>('ready'),[message,setMessage]=useState(''),[pending,setPending]=useState<PendingMint|null>(null),[assets,setAssets]=useState<Asset[]>([]),[checking,setChecking]=useState(false);
 const key=`veytos:mint:${network}:${packageAddress}:${initial.address}`;
 const eligibility=useQuery({queryKey:['eligibility',network,initial.address,address],queryFn:()=>chain().eligibility(initial.address,address),refetchInterval:15000});
 const drop=eligibility.data?.drop||initial;const data=eligibility.data;
 const status=data?dropStatus(drop,BigInt(data.now)):null;
 const rightNetwork=!!data&&networkMatches(data.chainId,wallet.network?.chainId);
 const preview=previewMint(drop,quantity,BigInt(data?.walletMinted||'0'),!!data);
 const max=preview.max;
 const locked=isUnresolved(phase)||checking;const total=preview.quote?.total.toString();
 useEffect(()=>{try{const raw=localStorage.getItem(key);if(raw){const p=pendingMintSchema.parse(JSON.parse(raw));if(p.network===network&&p.module===packageAddress&&p.drop===initial.address){setPending(p);setPhase('unknown');setMessage(p.hash?'A previous mint needs confirmation. Check its status before minting again.':'A wallet request was interrupted. Check your wallet activity before continuing.');}}}catch{setPhase('unknown');setMessage('Transaction storage is unavailable. Enable browser storage before minting.');}},[key,initial.address]);
 function save(p:PendingMint){
  // Before requesting a signature persistence is mandatory. After submission, keep
  // the hash in memory even if storage fails; never turn this into another mint.
  setPending(p);
  try{localStorage.setItem(key,JSON.stringify(p));}catch(e){if(!p.hash)throw e;}
 }
 function clearStored(){try{localStorage.removeItem(key);}catch{/* A stale record is reconciled safely on reload. */}}
 async function reconcile(p:PendingMint){if(!p.hash)return;setChecking(true);setPhase(p=>transactionTransition(p,'confirm',true));setMessage('Confirming your mint on Aptos…');try{for(let attempt=0;attempt<12;attempt++){
   const result=await chain().reconcile(p);
   if(result.status==='failed'){setPhase(p=>transactionTransition(p,'aborted',true));setMessage(readableError(new Error(result.message)));clearStored();return;}
   if(result.status==='success'){setAssets(result.assets);setPhase(p=>transactionTransition(p,'committed',true));setMessage('Your NFTs are now in your wallet.');trackBetaEvent('mint_completed',{quantity:p.quantity});clearStored();void client.invalidateQueries({queryKey:['eligibility']}).catch(()=>{});return;}
   await new Promise(r=>setTimeout(r,2000));
  }setPhase('unknown');setMessage('Confirmation is taking longer than usual. Your hash is saved; check again without submitting another mint.');
 }catch(error){reportClientError(error,'mint_reconciliation');setPhase('unknown');setMessage('Confirmation is unavailable right now. Your transaction may still succeed. Check its status again.');}finally{setChecking(false);}}
 async function review(){if(!address||!wallet.connected)return;setMessage('');try{const fresh=await eligibility.refetch();if(!fresh.data||fresh.error)throw new Error('RPC unavailable');if(!networkMatches(fresh.data.chainId,wallet.network?.chainId))throw new Error('Wrong network');if(fresh.data.paused||fresh.data.drop.admin_paused||fresh.data.drop.creator_paused)throw new Error('EPAUSED');const s=dropStatus(fresh.data.drop,BigInt(fresh.data.now));if(s!=='LIVE')throw new Error(s==='UPCOMING'?'ENOT_STARTED':s==='ENDED'?'EENDED':'ESUPPLY');validateQuantity(fresh.data.drop,quantity,BigInt(fresh.data.walletMinted));setPhase('review');dialog.current?.showModal();}catch(e){setPhase('failure');setMessage(readableError(e));}}
 async function mint(){if(signing.current||!address||locked)return;signing.current=true;dialog.current?.close();let requested=false;let p:PendingMint|null=null;
 try{if(localStorage.getItem(key))throw new Error('Unresolved transaction');const fresh=await chain().eligibility(initial.address,address);if(!networkMatches(fresh.chainId,wallet.network?.chainId))throw new Error('Wrong network');if(fresh.drop.terms.unit_price!==drop.terms.unit_price)throw new Error('EPRICE_CHANGED');if(fresh.paused||fresh.drop.creator_paused||fresh.drop.admin_paused)throw new Error('EPAUSED');if(dropStatus(fresh.drop,BigInt(fresh.now))!=='LIVE')throw new Error('Mint unavailable');validateQuantity(fresh.drop,quantity,BigInt(fresh.walletMinted));
 p={hash:'',sender:address,drop:initial.address,quantity,unitPrice:drop.terms.unit_price,network,module:packageAddress!};save(p);setPhase(p=>transactionTransition(p,'request',false));setMessage('Review the mint in your wallet. Network fees are additional.');trackBetaEvent('mint_started',{quantity});requested=true;
 const response=await wallet.signAndSubmitTransaction({data:chain().mintPayload(initial.address,quantity,drop.terms.unit_price)});
 if(!/^0x[\da-f]{64}$/i.test(response.hash))throw new Error('Unknown submission');p={...p,hash:response.hash};save(p);setPhase(p=>transactionTransition(p,'hash',true));setMessage('Transaction submitted. Verifying ownership and mint events…');await reconcile(p);
 }catch(e){reportClientError(e,'mint_submission');const rejected=definitiveRejection(e);if(p?.hash||(requested&&!rejected)){setPhase('unknown');setMessage(p?.hash?'Your transaction hash is retained. Check its status before minting again.':'No transaction hash was returned. Submission is not confirmed. Check wallet activity before taking another action.');}else{setPhase('failure');setMessage(readableError(e));if(requested)clearStored();}}finally{signing.current=false;}}
 const unavailable=!!(data?.paused||drop.admin_paused||drop.creator_paused);const primaryLabel=unavailable?'Mint paused':status==='UPCOMING'?'Mint opens soon':status==='ENDED'?'Mint ended':status==='SOLD OUT'?'Sold out':max===0?'Wallet limit reached':'Review mint';
 return <aside className="mint-panel" id="mint"><div className="between"><span className="eyebrow">PUBLIC MINT</span><DropStatus drop={drop}/></div><h2>Make it yours.</h2><div className="mint-price"><PriceDisplay octas={drop.terms.unit_price}/><span>per NFT</span></div><MintProgress minted={drop.minted} supply={drop.terms.max_supply}/><div className="mint-facts"><div><span>Available</span><strong>{(BigInt(drop.terms.max_supply)-BigInt(drop.minted)).toString()}</strong></div><div><span>Per wallet</span><strong>{drop.terms.wallet_limit} NFTs</strong></div><div><span>{status==='UPCOMING'?'Starts in':'Mint ends'}</span><strong>{status==='UPCOMING'?<Countdown target={drop.terms.start_seconds}/>:drop.terms.end_seconds==='0'?'When sold out':<Countdown target={drop.terms.end_seconds}/>}</strong></div></div>
 {phase==='success'?<div className="mint-success"><Check size={28}/><h3>A new addition to your collection.</h3><p>{drop.terms.name}</p>{assets.map(a=><a href={explorer('object',a.address)} target="_blank" rel="noreferrer" className="success-asset" key={a.address}><Artwork uri={a.uri} name={a.name}/><span>{a.name}<small>View token on Aptos ↗</small></span></a>)}<p className="caption transaction-hash">{pending?.hash}</p><ExternalLink href={explorer('txn',pending!.hash)}>View transaction</ExternalLink><a className="text-link" target="_blank" rel="noreferrer" href={`https://twitter.com/intent/tweet?text=${encodeURIComponent(`Just collected ${drop.terms.name} on ${brand.name}.`)}&url=${encodeURIComponent(`${window.location.origin}/collection/${initial.address}`)}`}>Share on X <ArrowUpRight size={14}/></a><button className="button primary" onClick={()=>{setPhase('ready');setMessage('');setPending(null);setAssets([]);}}>Mint another</button></div>:<><div className="between quantity-row"><label>Quantity</label><QuantitySelector value={quantity} max={max} disabled={locked} onChange={setQuantity}/></div><div className="between total"><span>Total mint price</span>{total?<PriceDisplay octas={total}/>:<span>—</span>}</div><p className="caption muted">Network fees are additional. The {Number(drop.terms.fee_bps)/100}% platform fee is included in the mint price.</p>
 {!wallet.connected?<WalletButton label="Connect to mint"/>:!rightNetwork&&data?<div className="notice warning" role="alert">Switch your wallet to Aptos {network} to mint.</div>:<button className="button primary" disabled={locked||!data||eligibility.isError||!rightNetwork||status!=='LIVE'||unavailable||!preview.quote} onClick={review}>{locked?'Transaction in progress':primaryLabel}<ArrowUpRight size={17}/></button>}
 {eligibility.isError&&<p className="notice error">Live mint data is unavailable. <button onClick={()=>eligibility.refetch()}>Try again</button></p>}
 {message&&<TransactionStatus phase={phase} hash={pending?.hash} message={message}/>}
 {phase==='unknown'&&pending?.hash&&<button className="button" disabled={checking} onClick={()=>reconcile(pending)}>Check transaction status</button>}
 {phase==='unknown'&&!pending?.hash&&pending&&<div className="recovery"><p>No submission is confirmed. If your wallet has a mint transaction, paste its hash to verify it. This never signs a new transaction.</p><input type="text" aria-label="Recovery transaction hash" placeholder="0x… transaction hash" value={recoveryHash} onChange={e=>setRecoveryHash(e.target.value)}/><button className="button" disabled={!/^0x[\da-f]{64}$/i.test(recoveryHash)||checking} onClick={()=>{const p={...pending,hash:recoveryHash};save(p);void reconcile(p);}}>Verify wallet transaction</button><label><input type="checkbox" checked={checkedWallet} onChange={e=>setCheckedWallet(e.target.checked)}/>I closed the wallet request and checked its activity: no transaction was signed or submitted.</label><button className="button" disabled={!checkedWallet||signing.current} onClick={()=>{clearStored();setPending(null);setPhase(p=>transactionTransition(p,'acknowledged-no-submission',false));setMessage('Request cleared after your confirmation. Nothing was automatically retried.');setCheckedWallet(false);}}>Clear unsubmitted request</button></div>}
 </>}
 <div className="mint-trust"><ShieldCheck size={15}/><span>Native Aptos assets. Yours to keep.</span></div>
 <dialog className="dialog" ref={dialog} aria-labelledby="review-title" onCancel={()=>setPhase('ready')}><div className="dialog-head"><span className="eyebrow">REVIEW TRANSACTION</span><button className="icon-button" aria-label="Close transaction review" onClick={()=>{dialog.current?.close();setPhase('ready');}}><X size={20}/></button></div><h2 id="review-title">Mint {quantity} {quantity===1?'NFT':'NFTs'}</h2><p>{drop.terms.name}</p><div className="review-summary"><div><span>Mint price</span>{total?<PriceDisplay octas={total}/>:<span>—</span>}</div><div><span>Included {brand.name} fee</span>{preview.quote?<PriceDisplay octas={preview.quote.fee.toString()}/>:<span>—</span>}</div><div><span>Creator receives</span>{preview.quote?<PriceDisplay octas={preview.quote.creatorRevenue.toString()}/>:<span>—</span>}</div><div><span>Network</span><strong>Aptos {network}</strong></div></div><p className="caption muted">Your wallet will show network fees before approval. Confirmed blockchain transactions cannot be undone.</p><button className="button primary" disabled={!preview.quote||locked||!rightNetwork} onClick={mint}>Confirm in wallet <ArrowUpRight size={17}/></button></dialog>
 </aside>;
}
